### ISSUE TITLE
Cross Team Integration - Tracker 

### ISSUE THREAD

**Issue by gbinal** [18F/API-All-the-X#180]
- [Derived from this list](https://github.com/18F/API-All-the-X/blob/gh-pages/pages/18f_internal_engagement.md).  
- [More notes here](https://docs.google.com/a/gsa.gov/document/d/1yL7aUcfe5nQicmsYvKLKhc4ufSxUgGrrvT5nAVcmyM8/edit).  
## Air Force Small Biz
- [x] Follows 18F API standards  
- [x] Uses api.data.gov (in roadmap)
- [x] Integrates API Usability 
- [ ] ~~Added to public data listing~~
- [x] Added to /developer page
- [x] Added to 18F's /developer page
- [x] Open source documentation
- [x] Discussing on API listserve  
- [ ] ~~Present at API meetup~~
# 
- [ ] ~~Offered any background on existing API efforts.~~
- [ ] Kept team up to date on any interactions with the agency.
- [ ] Inquired whether APIs are part of project; pitched them if not.
- [ ] Pitched that they consider promoting the /Developer Program offerings while dealing with the agency.
- [ ] Ask if they've found a team building APIs at the agency.  To let me know if they do.
- [ ] Ask if they haven't found any APIs that aren't listed in the /Developer Program status tracker.
- [ ] Pitched that they consider encouraging the US Government APIs listserve to anyone they come across who is working on or curious about APIs.
## API.Data.gov
- [ ] Follows 18F API standards  
- [x] Uses api.data.gov
- [x] Integrates API Usability 
- [x] ~~Added to public data listing~~
- [x] Added to /developer page 
- [x] Added to 18F's /developer page
- [x] Open source documentation
- [ ] Discussing on API listserve
- [ ] Present at API meetup 
# 
- [x] ~~Offered any background on existing API efforts.~~ 
- [x] ~~Kept team up to date on any interactions with the agency.~~ 
- [x] ~~Inquired whether APIs are part of project; pitched them if not.~~
- [x] ~~Pitched that they consider promoting the /Developer Program offerings while dealing with the agency.~~
- [x] ~~Ask if they've found a team building APIs at the agency.  To let me know if they do.~~ 
- [x] ~~Ask if they haven't found any APIs that aren't listed in the /Developer Program status tracker.~~
- [ ] Pitched that they consider encouraging the US Government APIs listserve to anyone they come across who is working on or curious about APIs.
## CAP Communicart (does have an api)
- [ ] Follows 18F API standards  
- [ ] Uses api.data.gov
- [ ] Integrates API Usability 
- [ ] ~~Added to public data listing~~
- [ ] Added to /developer page 
- [ ] Added to 18F's /developer page
- [ ] Open source documentation
- [ ] Discussing on API listserve
- [ ] Present at API meetup 
# 
- [ ] ~~Offered any background on existing API efforts.~~  
- [ ] ~~Kept team up to date on any interactions with the agency.~~  
- [ ] Inquired whether APIs are part of project; pitched them if not.  
- [ ] Pitched that they consider promoting the /Developer Program offerings while dealing with the agency.  
- [ ] Ask if they've found a team building APIs at the agency.  To let me know if they do.  
- [ ] Ask if they haven't found any APIs that aren't listed in the /Developer Program status tracker.
- [ ] Pitched that they consider encouraging the US Government APIs listserve to anyone they come across who is working on or curious about APIs.
## /Developer Program
- [x] ~~Follows 18F API standards~~  
- [x] ~~Uses api.data.gov~~
- [x] ~~Integrates API Usability~~ 
- [ ] Added to public data listing
- [x] Added to /developer page 
- [x] Added to 18F's /developer page
- [x] Open source documentation
- [x] Discussing on API listserve
- [x] Present at API meetup 
# 
- [x] ~~Offered any background on existing API efforts.~~  
- [x] ~~Kept team up to date on any interactions with the agency.~~  
- [x] ~~Inquired whether APIs are part of project; pitched them if not.~~  
- [x] ~~Pitched that they consider promoting the /Developer Program offerings while dealing with the agency.~~  
- [x] ~~Ask if they've found a team building APIs at the agency.  To let me know if they do.~~  
- [x] ~~Ask if they haven't found any APIs that aren't listed in the /Developer Program status tracker.~~
- [x] ~~Pitched that they consider encouraging the US Government APIs listserve to anyone they come across who is working on or curious about APIs.~~
## FBOpen
- [ ] Follows 18F API standards  
- [x] Uses api.data.gov
- [ ] Integrates API Usability 
- [ ] Added to public data listing
- [x] Added to /developer page 
- [x] Added to 18F's /developer page
- [x] Open source documentation
- [ ] Discussing on API listserve
- [x] Present at API meetup 
# 
- [x] Offered any background on existing API efforts.  
- [x] Kept team up to date on any interactions with the agency.  
- [x] Inquired whether APIs are part of project; pitched them if not.  
- [x] Pitched that they consider promoting the /Developer Program offerings while dealing with the agency.  
- [ ] Ask if they've found a team building APIs at the agency.  To let me know if they do.  
- [ ] Ask if they haven't found any APIs that aren't listed in the /Developer Program status tracker.
- [ ] Pitched that they consider encouraging the US Government APIs listserve to anyone they come across who is working on or curious about APIs.
## FOIA Modernization

Initial pitch sent.  
- [ ] Follows 18F API standards  
- [ ] Uses api.data.gov
- [ ] Integrates API Usability 
- [ ] Added to public data listing
- [ ] Added to /developer page 
- [ ] Added to 18F's /developer page
- [ ] Open source documentation
- [ ] Discussing on API listserve
- [ ] Present at API meetup 
# 
- [ ] Offered any background on existing API efforts.  
- [ ] Kept team up to date on any interactions with the agency.  
- [ ] Inquired whether APIs are part of project; pitched them if not.  
- [ ] Pitched that they consider promoting the /Developer Program offerings while dealing with the agency.  
- [ ] Ask if they've found a team building APIs at the agency.  To let me know if they do.  
- [ ] Ask if they haven't found any APIs that aren't listed in the /Developer Program status tracker.
- [ ] Pitched that they consider encouraging the US Government APIs listserve to anyone they come across who is working on or curious about APIs.
## OASIS

public in late january
- [ ] Follows 18F API standards  
- [x] Uses api.data.gov
- [x] Integrates API Usability 
- [ ] Added to public data listing
- [ ] Added to /developer page 
- [ ] Added to 18F's /developer page
- [ ] Open source documentation (pitched)
- [ ] Discussing on API listserve
- [ ] Present at API meetup 
# 
- [ ] Offered any background on existing API efforts.  
- [ ] Kept team up to date on any interactions with the agency.  
- [ ] Inquired whether APIs are part of project; pitched them if not.  
- [ ] Pitched that they consider promoting the /Developer Program offerings while dealing with the agency.  
- [ ] Ask if they've found a team building APIs at the agency.  To let me know if they do.  
- [ ] Ask if they haven't found any APIs that aren't listed in the /Developer Program status tracker.
- [ ] Pitched that they consider encouraging the US Government APIs listserve to anyone they come across who is working on or curious about APIs.
## openFEC

In discussions with Lindsay about.  
- [x] Follows 18F API standards  
- [ ] Uses api.data.gov
- [ ] Integrates API Usability 
- [ ] Added to public data listing
- [ ] Added to /developer page 
- [ ] Added to 18F's /developer page
- [ ] Open source documentation
- [ ] Discussing on API listserve
- [ ] Present at API meetup 
# 
- [x] Offered any background on existing API efforts.  
- [x] Kept team up to date on any interactions with the agency.  
- [x] Inquired whether APIs are part of project; pitched them if not.  
- [ ] Pitched that they consider promoting the /Developer Program offerings while dealing with the agency.  
- [x] Ask if they've found a team building APIs at the agency.  To let me know if they do.  
- [x] Ask if they haven't found any APIs that aren't listed in the /Developer Program status tracker.
- [ ] Pitched that they consider encouraging the US Government APIs listserve to anyone they come across who is working on or curious about APIs.
## Midas
- [ ] Follows 18F API standards  
- [ ] Uses api.data.gov
- [ ] Integrates API Usability 
- [ ] Added to public data listing
- [ ] Added to /developer page 
- [ ] Added to 18F's /developer page
- [ ] Open source documentation
- [ ] Discussing on API listserve
- [ ] Present at API meetup 
# 
- [ ] Offered any background on existing API efforts.  
- [ ] Kept team up to date on any interactions with the agency.  
- [ ] Inquired whether APIs are part of project; pitched them if not.  
- [ ] Pitched that they consider promoting the /Developer Program offerings while dealing with the agency.  
- [ ] Ask if they've found a team building APIs at the agency.  To let me know if they do.  
- [ ] Ask if they haven't found any APIs that aren't listed in the /Developer Program status tracker.
- [ ] Pitched that they consider encouraging the US Government APIs listserve to anyone they come across who is working on or curious about APIs.
## MyUSA
- [ ] Follows 18F API standards  
- [ ] Uses api.data.gov
- [ ] Integrates API Usability 
- [ ] Added to public data listing
- [ ] Added to /developer page 
- [ ] Added to 18F's /developer page
- [ ] Open source documentation
- [ ] Discussing on API listserve
- [ ] Present at API meetup 
# 
- [ ] Offered any background on existing API efforts.  
- [ ] Kept team up to date on any interactions with the agency.  
- [ ] Inquired whether APIs are part of project; pitched them if not.  
- [ ] Pitched that they consider promoting the /Developer Program offerings while dealing with the agency.  
- [ ] Ask if they've found a team building APIs at the agency.  To let me know if they do.  
- [ ] Ask if they haven't found any APIs that aren't listed in the /Developer Program status tracker.
- [ ] Pitched that they consider encouraging the US Government APIs listserve to anyone they come across who is working on or curious about APIs.
## Peace Corps
- [ ] Follows 18F API standards  
- [ ] Uses api.data.gov
- [ ] Integrates API Usability 
- [ ] Added to public data listing
- [ ] Added to /developer page 
- [ ] Added to 18F's /developer page
- [ ] Open source documentation
- [ ] Discussing on API listserve
- [ ] Present at API meetup 
# 
- [ ] Offered any background on existing API efforts.  
- [ ] Kept team up to date on any interactions with the agency.  
- [ ] Inquired whether APIs are part of project; pitched them if not.  
- [ ] Pitched that they consider promoting the /Developer Program offerings while dealing with the agency.  
- [ ] Ask if they've found a team building APIs at the agency.  To let me know if they do.  
- [ ] Ask if they haven't found any APIs that aren't listed in the /Developer Program status tracker.
- [ ] Pitched that they consider encouraging the US Government APIs listserve to anyone they come across who is working on or curious about APIs.
## USCIS
- [ ] Follows 18F API standards  
- [ ] Uses api.data.gov
- [ ] Integrates API Usability 
- [ ] Added to public data listing
- [ ] Added to /developer page 
- [ ] Added to 18F's /developer page
- [ ] Open source documentation
- [ ] Discussing on API listserve
- [ ] Present at API meetup 

Note - potential api contact with e-verify program
# 
- [ ] Offered any background on existing API efforts.  
- [ ] Kept team up to date on any interactions with the agency.  
- [ ] Inquired whether APIs are part of project; pitched them if not.  
- [ ] Pitched that they consider promoting the /Developer Program offerings while dealing with the agency.  
- [ ] Ask if they've found a team building APIs at the agency.  To let me know if they do.  
- [ ] Ask if they haven't found any APIs that aren't listed in the /Developer Program status tracker.
- [ ] Pitched that they consider encouraging the US Government APIs listserve to anyone they come across who is working on or curious about APIs.
## Web Maker / NotAlone.gov
- [ ] Follows 18F API standards  
- [ ] Uses api.data.gov
- [ ] Integrates API Usability 
- [ ] Added to public data listing
- [ ] Added to /developer page 
- [ ] Added to 18F's /developer page
- [ ] Open source documentation
- [ ] Discussing on API listserve
- [ ] Present at API meetup 
# 
- [ ] Offered any background on existing API efforts.  
- [ ] Kept team up to date on any interactions with the agency.  
- [ ] Inquired whether APIs are part of project; pitched them if not.  
- [ ] Pitched that they consider promoting the /Developer Program offerings while dealing with the agency.  
- [ ] Ask if they've found a team building APIs at the agency.  To let me know if they do.  
- [ ] Ask if they haven't found any APIs that aren't listed in the /Developer Program status tracker.
- [ ] Pitched that they consider encouraging the US Government APIs listserve to anyone they come across who is working on or curious about APIs.
## Web Maker / myRA
- [ ] Follows 18F API standards  
- [ ] Uses api.data.gov
- [ ] Integrates API Usability 
- [ ] Added to public data listing
- [ ] Added to /developer page 
- [ ] Added to 18F's /developer page
- [ ] Open source documentation
- [ ] Discussing on API listserve
- [ ] Present at API meetup 
# 
- [ ] Offered any background on existing API efforts.
- [ ] Kept team up to date on any interactions with the agency.  
- [ ] Inquired whether APIs are part of project; pitched them if not.  
- [ ] Pitched that they consider promoting the /Developer Program offerings while dealing with the agency.  
- [ ] Ask if they've found a team building APIs at the agency.  To let me know if they do.  
- [ ] Ask if they haven't found any APIs that aren't listed in the /Developer Program status tracker.
- [ ] Pitched that they consider encouraging the US Government APIs listserve to anyone they come across who is working on or curious about APIs.
## Web Maker / EITI
- [ ] Follows 18F API standards  
- [ ] Uses api.data.gov
- [ ] Integrates API Usability 
- [ ] Added to public data listing
- [ ] Added to /developer page 
- [ ] Added to 18F's /developer page
- [ ] Open source documentation
- [ ] Discussing on API listserve
- [ ] Present at API meetup 
# 
- [ ] Offered any background on existing API efforts.  
- [ ] Kept team up to date on any interactions with the agency.  
- [ ] Inquired whether APIs are part of project; pitched them if not.  
- [ ] Pitched that they consider promoting the /Developer Program offerings while dealing with the agency.  
- [ ] Ask if they've found a team building APIs at the agency.  To let me know if they do.  
- [ ] Ask if they haven't found any APIs that aren't listed in the /Developer Program status tracker.
- [ ] Pitched that they consider encouraging the US Government APIs listserve to anyone they come across who is working on or curious about APIs.
